[book]
authors = ["axodotdev"]
language = "en"
multilingual = false
src = "src"

[output.markdown]
[output.html]
edit-url-template = "https://github.com/axodotdev/oranda/edit/main/docs/{path}"
search.use-boolean-and = true
